steps:
  # clones project so it can be setup & tested
  # All steps after this must set working directory to use the cloned project source

  # $COMMIT_SHA is a default gcloud env var, to run via cloudbuild submit use:
  # gcloud builds submit --substitutions COMMIT_SHA=<commit sha>,REPO_NAME=solo-io/valet ./
  - name: 'gcr.io/$PROJECT_ID/prepare-go-workspace:0.3.0'
    args:
      - "--repo-name"
      - "$REPO_NAME"
      - "--repo-sha"
      - "$COMMIT_SHA"
      - "--repo-output-dir"
      - "."
    env:
      - 'GIT_SSH_CONFIG=FALSE'
    id: 'prepare-workspace'

  - name: gcr.io/cloud-builders/gsutil
    entrypoint: 'bash'
    args: ['-c', 'mkdir -p /go/pkg && cd /go/pkg && gsutil cat gs://$PROJECT_ID-cache/valet/valet-mod.tar.gz | tar -xzf -']
    dir: &dir '/workspace/valet'
    id: 'untar-mod-cache'

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker login quay.io --username "solo-io+solobot" --password $$QUAY_IO_PASSWORD']
    env:
      - 'DOCKER_CONFIG=/workspace/docker-config'
    secretEnv: ['QUAY_IO_PASSWORD']
    waitFor: ['-']
    id: 'docker-login'

  - name: 'gcr.io/$PROJECT_ID/go-mod-make:0.2.1'
    dir: *dir
    args: ['build']
    id: 'build'
    waitFor: ['prepare-workspace']

  - name: 'gcr.io/$PROJECT_ID/go-mod-ginkgo:0.2.0'
    dir: *dir
    env:
      - 'BUILD_ID=$BUILD_ID'
    args: ['-r', '-p', '-failFast', '-randomizeSuites', '-randomizeAllSpecs', '-skipPackage=./test,./cli']
    waitFor: ['build']
    id: 'test'

secrets:
  - kmsKeyName: projects/solo-public/locations/global/keyRings/build/cryptoKeys/build-key
    secretEnv:
      QUAY_IO_PASSWORD: CiQABlzmSRx5TcOqbldXa/d/+bkmAfpNAWa3PTS06WvuloZL+vASaQCCPGSGCogonVZVEUNx4G3YJtWi18gSuNx4PvLe08q8xAflTMFkjsyQirAOK3Y2oCvgYwiw/ITcuydjkpMjxDygFyENXS9FKFJoAXHlPQE5qidKr8xxmxF5ezhmjGB0gjyjXIIkbSEnBg==
#      GITHUB_TOKEN: CiQABlzmSYYiveU0gTxGH2139eaBUedjV3vNCxQmJU+nRPlfQ/YSUQCCPGSGzbGp49fwDYuefAx9V94b8mivdp9AqB7zQAa07VtGJmrGdg9ZuhKGFrrgqxwABE0LLVNHyngCSHYSYMH8Vn/mRtT7wQuEHBlKVGtqPw==
#      LICENSE_KEY: CiQABlzmSRdJEuvgFYroRQ/Vhrc7hWRJGL0oh1IATx87+Zdm42gSlQEAgjxkhvAVivUON4YnNGsRXZPG1tEOHWl1DzDHyfa+6gAD5fZsUQnjVqSZMAs18ojBofnGEzRTrv6CtXQGpFBkIrG7nLA4VyOIHl4ss0UWyVtNcGb6FSMpIr9j/d8UrODEoO8C+f21/YMDO7T1fCS3NC7KFvBABM3f0GUVtI6r+//LL0uQuotEMxv+gyywgxU2rhKHSg==
#      AWS_SECRET_ACCESS_KEY: CiQABlzmSQANzc6+9afLmCUyiTF0qYwrC+WB8i/toet94WMH26QSUQCCPGSGd8bak18TDObvnI+NsaIaslKtvAdfUEJ8XeujmfXUhGr69aUIuzhEDZXdRMnUDGcYpxe1qNzawO89dzRGs8hSiL9XHFXR6B9BjB9g1g==
#      AWS_ACCESS_KEY_ID: CiQABlzmSftZa9ES/WKM6/qeTyRV1BBCu14GSjC7vtDiCk1HeL4SPQCCPGSGfwYy0bHyzbeNsU/0rtwwqBRDe1A46A48+ANx7/1KuVsotS1mYLWmoofN+4JBMmA8WafmJcI+3dE=

timeout: 1800s