apiVersion: gateway.solo.io/v1
kind: VirtualService
metadata:
  name: glooui
  namespace: gloo-system
spec:
  virtualHost:
    domains:
      - "*"
    name: gloo-system.glooui
    routes:
      - matcher:
          prefix: /
        routeAction:
          single:
            upstream:
              name: gloo-system-apiserver-ui-8080
              namespace: gloo-system
    virtualHostPlugins:
      extensions:
        configs:
          extauth:
            basicAuth:
              realm: "test"
              apr:
                users:
                  user:
                    salt: "TYiryv0/"
                    hashedPassword: "8BvzLUO9IfGPGGsPnAgSu1"